name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          yarn global add netlify-cli
          "$(yarn global bin)/netlify" deploy --dir=build --prod --message "${{ steps.changelog.outputs.tag }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
